# Generated by Django 5.1.3 on 2025-09-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
            },
        ),
        migrations.AlterModelOptions(
            name="notificationreceiver",
            options={"verbose_name": "Получатель", "verbose_name_plural": "Получатели"},
        ),
        migrations.AddField(
            model_name="notification",
            name="sent_by_service",
            field=models.CharField(
                blank=True,
                choices=[("telegram", "Telegram"), ("email", "Email"), ("sms", "SMS")],
                max_length=20,
                null=True,
                verbose_name="Сервис отправки",
            ),
        ),
    ]
