# Generated by Django 5.1.3 on 2025-09-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="sent_by_service",
            new_name="sent_via_service",
        ),
    ]
