# Generated by Django 5.1.3 on 2025-09-28 19:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_rename_sent_by_service_notification_sent_via_service"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="receivers",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="sent_at",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="sent_via_service",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="status",
        ),
        migrations.AddField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="users",
            field=models.ManyToManyField(
                related_name="notifications",
                through="notifications.NotificationReceiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationreceiver",
            name="channel",
            field=models.CharField(
                blank=True,
                choices=[("telegram", "Telegram"), ("email", "Email"), ("sms", "SMS")],
                max_length=20,
                null=True,
                verbose_name="Способ отправки",
            ),
        ),
        migrations.AddField(
            model_name="notificationreceiver",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время отправки"
            ),
        ),
        migrations.AddField(
            model_name="notificationreceiver",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает отправки"),
                    ("sent", "Отправлено"),
                    ("failed", "Ошибка"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="notificationreceiver",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receivers",
                to="notifications.notification",
            ),
        ),
    ]
