# Generated by Django 5.1.3 on 2025-09-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_notificationlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="duration_seconds",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Время выполнения (c)"
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Завершено"),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="total_failed",
            field=models.PositiveIntegerField(default=0, verbose_name="Ошибки"),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="total_sent",
            field=models.PositiveIntegerField(default=0, verbose_name="Отправлено"),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="total_users",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Всего получателей"
            ),
        ),
    ]
