# Generated by Django 5.1.3 on 2025-09-27 16:19

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                unique=True,
                verbose_name="Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Telegram ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Telegram username"
            ),
        ),
    ]
