# Generated by Django 5.1.3 on 2025-09-28 20:27

from django.db import migrations, models
import uuid


def generate_telegram_tokens(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all():
        if not user.telegram_token:
            user.telegram_token = uuid.uuid4()
            user.save(update_fields=["telegram_token"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_user_options_alter_user_email_alter_user_phone_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(generate_telegram_tokens, reverse_code=migrations.RunPython.noop),
    ]
