# Generated by Django 5.1.3 on 2025-09-28 21:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_telegram_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
